// <auto-generated />
using Employee.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Employee.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Employee.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designation = "Full Stack Developer",
                            Name = "Jay krishna Reddy"
                        },
                        new
                        {
                            Id = 2,
                            Designation = "SSE",
                            Name = "JK"
                        },
                        new
                        {
                            Id = 3,
                            Designation = "Software Engineer",
                            Name = "Jay"
                        },
                        new
                        {
                            Id = 4,
                            Designation = "Database Developer",
                            Name = "krishna Reddy"
                        },
                        new
                        {
                            Id = 5,
                            Designation = "Cloud Engineer",
                            Name = "Reddy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
